version: '3.3'
services:
  db_brn:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: brn
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  brn:
    container_name: brn
    command: java -jar build/libs/epam-brn.jar --Dspring.profiles.active=prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    environment:
      POSTGRES_DB: brn
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      SPRING_PROFILE: prod